[2025-09-03T15:12:23.179+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-03T15:12:23.192+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T15:12:22.099738+00:00 [queued]>
[2025-09-03T15:12:23.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T15:12:22.099738+00:00 [queued]>
[2025-09-03T15:12:23.197+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-03T15:12:23.202+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_for_interval> on 2025-09-03 15:12:22.099738+00:00
[2025-09-03T15:12:23.206+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'cs_ingestion_monthly', 'fetch_for_interval', 'manual__2025-09-03T15:12:22.099738+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_cs.py', '--cfg-path', '/tmp/tmpzadvl7sd']
[2025-09-03T15:12:23.207+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=442) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-03T15:12:23.207+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask fetch_for_interval
[2025-09-03T15:12:23.207+0000] {standard_task_runner.py:63} INFO - Started process 447 to run task
[2025-09-03T15:12:23.227+0000] {task_command.py:426} INFO - Running <TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T15:12:22.099738+00:00 [running]> on host 18f4cd224f83
[2025-09-03T15:12:23.342+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cs_ingestion_monthly' AIRFLOW_CTX_TASK_ID='fetch_for_interval' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T15:12:22.099738+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-03T15:12:22.099738+00:00'
[2025-09-03T15:12:23.342+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-03T15:12:23.343+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-03T15:12:23.343+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_cs.py", line 46, in fetch_for_interval
    from ingestion.ingestion_cs import build_cs_query, fetch_window
ModuleNotFoundError: No module named 'ingestion'
[2025-09-03T15:12:23.347+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=cs_ingestion_monthly, task_id=fetch_for_interval, run_id=manual__2025-09-03T15:12:22.099738+00:00, execution_date=20250903T151222, start_date=20250903T151223, end_date=20250903T151223
[2025-09-03T15:12:23.351+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task fetch_for_interval (No module named 'ingestion'; 447)
[2025-09-03T15:12:23.394+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-03T15:12:23.403+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-03T15:12:23.405+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
