[2025-09-03T15:20:41.175+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T15:20:38.273600+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
